### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by andhicapratama** [qiscus/qiscus-chat-sdk-android-sample#1]
![qiscuc](https://user-images.githubusercontent.com/32853639/55541071-6ba9b500-56ee-11e9-87ae-5a66015fc2e0.PNG)

it cannot build the project, how to solve this. I already click the link and download that file. But i dont know how to do next

**Comment by rajapulau** [comment]
what version of android studio do you use ? You can check version plugin and gradle version here https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle. I'm using Android Studio 3.3 it's working.

**Comment by andhicapratama** [comment]
I also using android studio 3.3.2 …. when I imported project it showing that error.. am I missing something

**Comment by adicatur** [comment]
Hi @andhicapratama can we know the detail error message from the logcat or event log in android studio ? thanks

**Comment by rajapulau** [comment]
Can you explain importing the project you was did ? basic to run this project, just `git clone` and `gradle sync`

**Comment by ariefnurputranto** [comment]
![Screen Shot 2019-04-05 at 17 21 56](https://user-images.githubusercontent.com/12388348/55621320-61a7b500-57c7-11e9-8efe-cc52c141833d.png)

check this image, and  refer version plugin and gradle version here https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle

for example we using, 
![Screen Shot 2019-04-05 at 17 24 56](https://user-images.githubusercontent.com/12388348/55621460-c105c500-57c7-11e9-8e3d-711a371a4a99.png)

**Comment by andhicapratama** [comment]
yes I clone from git .. and when I open it on Android Studio it build that project first automatically.. But it Showing that error … I already check the version of Android Studio is 3.3.2. dependency, classpath and distribution url already the same like in GitHub. 

ERROR: The specified Gradle distribution 'https://services.gradle.org/distributions/gradle-4.6-all.zip' does not appear to contain a Gradle distribution.

**Comment by ariefnurputranto** [comment]
![Screen Shot 2019-04-08 at 19 14 29](https://user-images.githubusercontent.com/12388348/55723371-1e517e80-5a33-11e9-8f92-3366e1e5d501.png)

can you share screenshoot build.gradle sir?
